// <auto-generated />
namespace Exiger.JWT.Core.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialdatabasesetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialdatabasesetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060509418_initial-database-setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
